#!/usr/bin/env racket
#lang racket

;; variables and functions
(define (bind mod whichkey action)
  (let([command (string-append-immutable "riverctl  map  normal"  mod  whichkey "spawn"  action)])
    (lambda()
      (system command))))

(define (exec param)
  (system(string-append-immutable "riverctl " "spawn " param))) ; -> uses riverctl to launch applications


(define menu "fuzzel") ; -> set the menu variable to fuzzel launcher
(define term "footclient") ; -> set the terminal to foot client: foot server should be autostarted
(define wlogout "wlogout")

;; autostart
(exec "foot --server") ; autostart foot server
(exec "mako") ; notifications
;; (exec "kanshi") ; outputs
(exec "waybar") ; status bar
(exec "swaybg -i ~/Pictures/Wallpapers/Sway/Sway_Wallpaper_Blue_1920x1080.png")

;; keybindings
(bind "Super" "Return" term)
(bind "Super" "e" wlogout)
(bind "Super" "d" menu)

;; workspaces
(let ((workspaces '(1 2 3 4 5 6 7 8 9)))
  (for ([i workspaces])
    (print i)
    (let ((tag_number
           (system(1 << ($i - 1)))))
      (string-append-immutable "riverctl map normal Super " (string i) " set-focused-tags" (string all_tags)))))
