#!/usr/bin/env racket
#lang racket

;; variables and functions
(define (bind key1 key2 action)
  (let([command (string-append-immutable "riverctl " "map " "normal " key1 " " key2 " " "Spawn " action)])
    (lambda()
      (system command))))

(define (exec param)
  (system(string-append-immutable "riverctl " "spawn " param))) ; -> uses riverctl to launch applications

(define menu "fuzzel") ; -> set the menu variable to fuzzel launcher
(define term "footclient") ; -> set the terminal to foot client: foot server should be autostarted
(define wlogout "wlogout")

;; autostart
(exec "foot --server") ; autostart foot server
(exec "mako") ; notifications
;; (exec "kanshi") ; outputs
(exec "waybar") ; status bar

;; keybindings
(bind "Super" "Return" term)
(bind "Super" "e" wlogout)
